 
language: c
dist: xenial

env:
  - UPLOADTOOL_ISPRERELEASE=true

# Install dependencies
install:
  - sudo add-apt-repository -y ppa:cos-lyk/libmpv-xenial
  - sudo apt-get update
  - sudo apt-get install -y -t xenial-backports meson
  - sudo apt-get install -y curl desktop-file-utils libepoxy-dev libgtk-3-dev libjson-glib-dev libmpv-dev valac

script:
  - meson build --prefix=/usr --buildtype=release
  - ninja -C build

after_success:
  - DESTDIR=. ninja -C build install
  - wget -c https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage
  - chmod +x pkg2appimage
  - ./pkg2appimage appimage.yml
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
