 
language: c
dist: xenial

env:
  - UPLOADTOOL_ISPRERELEASE=true

# Install dependencies
install:
  - sudo add-apt-repository -y ppa:cos-lyk/libmpv-xenial
  - sudo apt-get update
  - sudo apt-get install -y -t xenial-backports ninja
  - sudo apt-get install -y curl desktop-file-utils ffmpeg libepoxy-dev libgtk-3-dev libjson-glib-dev libmpv-dev valac
  - pip3 install meson

script:
  - meson build --prefix=/usr --buildtype=release
  - ninja -C build

after_success:
  - DESTDIR=$PWD/AppDir ninja -C build install
  - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - chmod +x linuxdeploy*.AppImage
  - ./linuxdeploy-x86_64.AppImage --plugin gtk3 --appdir AppDir --executable /usr/bin/ffmpeg --executable /usr/bin/ffprobe --output appimage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Video_Splitter-*.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
